// <auto-generated />
using System;
using DataEdge_CustomerService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataEdge_CustomerService.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataEdge_CustomerService.Persistence.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("NetPrice")
                        .HasColumnType("real");

                    b.Property<int>("PartnerId")
                        .HasColumnType("integer");

                    b.Property<string>("QuantitativeUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("DataEdge_CustomerService.Persistence.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CashRegisterId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PartnerId")
                        .HasColumnType("integer");

                    b.Property<float>("PurchaseAmount")
                        .HasColumnType("real");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Purchase", (string)null);
                });

            modelBuilder.Entity("DataEdge_CustomerService.Persistence.Entities.PurchaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Gross")
                        .HasColumnType("real");

                    b.Property<int?>("PartnerCtID")
                        .HasColumnType("integer");

                    b.Property<int>("PartnerID")
                        .HasColumnType("integer");

                    b.Property<int?>("PurchaseID")
                        .HasColumnType("integer");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PartnerCtID")
                        .IsUnique();

                    b.HasIndex("PurchaseID");

                    b.ToTable("PurchaseItem", (string)null);
                });

            modelBuilder.Entity("DataEdge_CustomerService.Persistence.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PartnerID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Shop", (string)null);
                });

            modelBuilder.Entity("DataEdge_CustomerService.Persistence.Entities.Purchase", b =>
                {
                    b.HasOne("DataEdge_CustomerService.Persistence.Entities.Shop", "Shop")
                        .WithMany("Purchases")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Shop_ShopID");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("DataEdge_CustomerService.Persistence.Entities.PurchaseItem", b =>
                {
                    b.HasOne("DataEdge_CustomerService.Persistence.Entities.Item", "Item")
                        .WithOne("PurchaseItem")
                        .HasForeignKey("DataEdge_CustomerService.Persistence.Entities.PurchaseItem", "PartnerCtID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Item_ItemID");

                    b.HasOne("DataEdge_CustomerService.Persistence.Entities.Purchase", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Purchase_PurchaseID");

                    b.Navigation("Item");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("DataEdge_CustomerService.Persistence.Entities.Item", b =>
                {
                    b.Navigation("PurchaseItem");
                });

            modelBuilder.Entity("DataEdge_CustomerService.Persistence.Entities.Purchase", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("DataEdge_CustomerService.Persistence.Entities.Shop", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
